name: formatting-$(Date:yyyyMMdd)$(Rev:.r)

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.12'
  pathsToCheck: 'app functions'

stages:
- stage: LintAndFormat
  displayName: Format & Lint (black + flake8)
  jobs:
  - job: checks
    displayName: Run black & flake8
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install black flake8
      displayName: Install tools

    - script: |
        echo "Running Black (check only; config from pyproject.toml)"
        black --check --diff $(pathsToCheck)
      displayName: Black (check only)

    - script: |
        echo "Running Flake8 (config from .flake8)"
        flake8 $(pathsToCheck)
      displayName: flake8